### ISSUE TITLE
lessThen

### ISSUE THREAD

**Issue by nkovacs** [Codeception/Verify#12]
It should be lessThan. There are already two pull requests, #6 and #10. Please fix this.

**Comment by bbatsche** [comment]
Hey @nkovacs, you may be interested in [my fork of Verify](http://github.com/bbatsche/Verify). It's not quite a seamless drop in replacement, but it includes all the existing functionality of Codeception/Verify, plus virtually all the available assertions built into PHPUnit. The existing methods have been renamed to optimize for clarity and ensure code reads as near to English as possible. Plus, it fixes the `lessThen` typo. :wink: It's available in [Packagist as well](https://packagist.org/packages/bbat/verify).

**Comment by nkovacs** [comment]
Thanks, I'll check it out.
