### ISSUE TITLE
Problem with newest versions

### ISSUE THREAD

**Issue by tranfuga25s** [Codeception/Verify#13]
When using this library with phpunit 3.7 and codeception 1.8.7 all the statements must be setted inside a block like
```
if ($scenario->running()) {
}
```
because the getter functions are returning a maybe object.

If no change is possible, say it explicitly on the readme file.

**Comment by DavertMik** [comment]
i don't think that issues with Codeception 1.x and PHPUnit 3.x is really actual these days... 
`$scenario->running` was the limitation of Codeception 1.x and not related to verify. We fixed that in 2.0
