### ISSUE TITLE
Tag 0.3.2?

### ISSUE THREAD

**Issue by greg-1-anderson** [Codeception/Verify#26]
Thank you for merging #25.  However, VersionEye will not pull license info out of the composer.json file of the dev-master release; it is apparently still looking at the most recent tagged version (0.3.1).  Would you mind tagging an 0.3.2 release, so that we can make our VersionEye license report come out clean?

Very minor issue, to be sure, but appreciated if you have a chance.

**Comment by DavertMik** [comment]
Sure, why not

**Comment by greg-1-anderson** [comment]
Thanks!

**Comment by greg-1-anderson** [comment]
Could someone kindle go to https://packagist.org/packages/codeception/verify and hit the "Update" button -- maybe set up automatic updates too?

**Comment by sergeyklay** [comment]
@DavertMik

**Comment by Naktibalda** [comment]
I see 0.3.2 in https://packagist.org/packages/codeception/verify now.

**Comment by greg-1-anderson** [comment]
Yes,  thanks, our VersionEye checks are passing now!
