### ISSUE TITLE
Feature Enhancement:  Return $actual, $expected, and $description

### ISSUE THREAD

**Issue by NoMan2000** [Codeception/Verify#28]
Currently the code works like this:

    if ( ! $this->isFileExpectation ) {
            a::assertEquals($expected, $this->actual, $this->description);
        } else {
            a::assertFileEquals($expected, $this->actual, $this->description);
        }

With void/no return.  But I'd like to be able to turn return those three values each time as an array.  For example, I call the `verify` function from the web code on a testing page. 

![screen shot 2016-11-21 at 12 52 58 pm](https://cloud.githubusercontent.com/assets/812215/20496125/818e10fe-afe9-11e6-8128-91739527e9a5.png)

I extended Verify and returned those values from each of the different callers.  Now I can run tests on demand through the web.

**Comment by DavertMik** [comment]
We improved extending options in 1.0. See Readme
