### ISSUE TITLE
Feature request: upgrade PHPUnit to v6 (namespaces)

### ISSUE THREAD

**Issue by cedx** [Codeception/Verify#30]
The latest version of `PHPUnit` is based on namespaces. `Verify` is currently not compatible with this new version. It would be cool if `Verify` API was updated to the latest `PHPUnit` API.

**Comment by Shockwave2k** [comment]
This would do the Trick for both versions.
https://github.com/Codeception/Verify/pull/31

**Comment by DavertMik** [comment]
Fixed by @Shockwave2k
