### ISSUE TITLE
Class alias breaks code

### ISSUE THREAD

**Issue by kevinpapst** [Codeception/Verify#33]
Hi guys,

I followed some open and closed PRs related to class aliasing, which try to handle different PHPUnit versions. But in my case it breaks dev env when using the PHPUnit v4 version >= 4.8.35.

[This code](https://github.com/sebastianbergmann/phpunit/blob/4.8/src/ForwardCompatibility/Assert.php) already takes care of what you are trying to achieve ... 

If I remove the first three lines in [function.php](https://github.com/Codeception/Verify/blob/master/src/Codeception/function.php#L2) everything is working as expected, but I still can't wrap my around what is going on exactly. 

I receive the error 
`PHP Fatal error:  Class 'PHPUnit_Framework_Assert' not found in /vendor/phpunit/phpunit/src/ForwardCompatibility/Assert.php on line 16`

I guess its because you are autoloading the namespaced version before composer applied the classmapping for the old style class and thus can't load the class you are trying to aliasing.

Maybe you have an idea what exactly is going on and also if your workaround code is still required. Maybe its not a good idea to interfere with applications autoloading in that way?

And not to forget: thanks for building Codeception, its a great tool! :-)

Thanks,
Kevin

**Comment by Naktibalda** [comment]
I think that it would be the best to remove class alias, replace class name with namespaced and set correct  ranges of supported versions of PHPUnit in composer.json
And it should be in require section, not in require-dev.

**Comment by kevinpapst** [comment]
Sounds good. If the user loads an incompatible of PHPUnit version its up to him to fix the problem. I believe thats what I did ;-) If PHPUnit 4 is not supported, just put it in composer.json and in README.

**Comment by DavertMik** [comment]
> I think that it would be the best to remove class alias, replace class name with namespaced and set correct ranges of supported versions of PHPUnit in composer.json
And it should be in require section, not in require-dev.

Thanks, that's what I'm doing now :)

**Comment by DavertMik** [comment]
Version 1.0 will support only PHPUnit 6+
