### ISSUE TITLE
Verify/expect steps doesn't shows in codeception report

### ISSUE THREAD

**Issue by Rekadze** [Codeception/Verify#34]
Hi there.
i'm trying to use 'verify' instead of codeception assertions.
But 'verify/expect' steps doesn't appears in codeception report if they are pass. And it's a bit annoying

Do you have any suggestions how to put them into report? 
And of course I'd like to see the description from 'verify/expect' steps into report too.

**Comment by Rekadze** [comment]
@DavertMik Any ideas?

**Comment by DavertMik** [comment]
Sorry, they use PHPUnit API and they are not Codeception steps. 
So they won't be shown in reports, unfortunately.

It would be interesting to make them run as Codeception steps but no real plans to do that. 😞
